// OTOMATİK ÜRETİLDİ — "AI LAB Kitap Listesi.xlsx" (75 kitap) + kapaklar
// (Open Library / Google Books). Yeniden üretim: scripts/fetch-book-covers.py.
// Kapağı bulunamayanlar null — admin panelinden kapak URL'i elle eklenebilir.

export interface SeedBook {
  id: string;
  title: string;
  author: string;
  category: string;
  description: string;
  coverImageUrl: string | null;
  totalCopies: number;
}

export const SEED_BOOKS: SeedBook[] = [
  {
    id: "book_xl_001",
    title: "50 Soruda Yapay Zekâ",
    author: "Cem Say",
    category: "Giriş",
    description: "Türk yazar, orijinal Türkçe popüler bilim · Bilim ve Gelecek Kitaplığı · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/10838611-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_002",
    title: "Yaşam 3.0: Yapay Zekâ Çağında İnsan Olmak",
    author: "Max Tegmark",
    category: "Giriş",
    description: "AI ve gelecek üzerine en popüler giriş · Pegasus · 2019",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_003",
    title: "Master Algoritma",
    author: "Pedro Domingos",
    category: "Giriş",
    description: "Baskısı tükenmiş, Nadir Kitap'tan · Paloma Yayınları · 2017",
    coverImageUrl: null,
    totalCopies: 1,
  },
  {
    id: "book_xl_004",
    title: "Makine Öğrenmesi",
    author: "Ethem Alpaydın",
    category: "Giriş",
    description: "MIT Press Essential Knowledge TR baskısı · Boğaziçi Üniversitesi Yayınevi · 2017",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_005",
    title: "Veri Bilimi",
    author: "John D. Kelleher & Brendan Tierney",
    category: "Giriş",
    description: "MIT Press Essential Knowledge TR; veri biliminin felsefesi · Tellekt · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12269965-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_006",
    title: "Üretici Yapay Zeka: Temel Bilgiler",
    author: "Henrik Kniberg",
    category: "Giriş",
    description: "Viral video kitap; el çizimli, pratik GenAI rehberi · Leanpub (dijital) · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_007",
    title: "Veri Bilimi ve Analitiği (Giriş)",
    author: "Yüksel Yurtay (Dr.)",
    category: "Giriş",
    description: "Türk yazar, iş zekası ve stratejik karar alma · Ekin Kitabevi · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_008",
    title: "Why Machines Learn: The Elegant Math Behind Modern AI",
    author: "Anil Ananthaswamy",
    category: "Giriş",
    description: "Modern AI'nın ardındaki matematiği hikâyeleştiren popüler bilim · Dutton · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_009",
    title: "Yapay Öğrenme",
    author: "Ethem Alpaydın",
    category: "Uygulama",
    description: "Türk yazar, ML referans · Boğaziçi Üniversitesi Yayınevi · 2013",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12255229-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_010",
    title: "Tensorflow ile Derin Öğrenme",
    author: "Ümit Tunç",
    category: "Uygulama",
    description: "Türk yazar, Python + TF + Keras + CNN + GAN · Kodlab Yayın Dağıtım · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12213684-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_011",
    title: "Python: Veri Analizi, Görselleştirme ve Yapay Zekâ",
    author: "Ayhan Bozkurt",
    category: "Uygulama",
    description: "NumPy, Pandas, Scikit-learn, PyTorch — tek kaynak · Kitapyurdu Doğrudan Yayıncılık · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_012",
    title: "Yapay Zeka: Derin Öğrenme, Stratejili Oyunlar, NLP",
    author: "Vasif Nabiyev",
    category: "Uygulama",
    description: "Türk akademisyen, 6. baskı · Seçkin Yayıncılık · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_013",
    title: "Yapay Zekâyı Kodlamak",
    author: "Özlem Sebetci Ural",
    category: "Uygulama",
    description: "Python ile denetimli/denetimsiz/pekiştirmeli öğrenme · Seçkin Yayıncılık · 2023",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_014",
    title: "Uygulamalar ile Python ve Yapay Zekâ",
    author: "Emrah Aydemir",
    category: "Uygulama",
    description: "Türk akademisyen, 100+ örnek uygulama · Akademisyen Kitabevi · 2021",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_015",
    title: "Yapay Zeka Mühendisliği Seti (4 Kitap)",
    author: "Kolektif",
    category: "Uygulama",
    description: "AI + Derin Öğrenme + MATLAB + Python 3 · Kodlab Yayın Dağıtım · 2019",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_016",
    title: "Veri Bilimi İçin Python",
    author: "Bülent Çobanoğlu",
    category: "Uygulama",
    description: "Türk yazar, 512 sayfa kapsamlı · Kodlab Yayın Dağıtım · 2021",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_017",
    title: "Veri Bilimi İçin Python (Çözümlü Örnekler)",
    author: "Burak Özkan & Yalçın Özkan",
    category: "Uygulama",
    description: "Türk yazar, NumPy/Pandas/scikit ile uygulamalar · Papatya Bilim Yayınevi · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_018",
    title: "Hands-On Machine Learning with Scikit-Learn and PyTorch",
    author: "Aurélien Géron",
    category: "Uygulama",
    description: "Géron'un 2025 yeni baskısı: PyTorch, Hugging Face, LLM fine-tuning, RL ajanları · O'Reilly · 2025",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15138297-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_019",
    title: "Deep Learning with Python (3. baskı)",
    author: "François Chollet & Matthew Watson",
    category: "Uygulama",
    description: "Keras kurucusundan 2025 baskısı: Keras 3, PyTorch, JAX, kendi GPT'ni ve difüzyon modelini kur · Manning · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_020",
    title: "Build a Large Language Model (from Scratch)",
    author: "Sebastian Raschka",
    category: "Uygulama",
    description: "LLM'i PyTorch ile sıfırdan kodlama · Manning · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15225524-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_021",
    title: "Yorumlanabilir ve Açıklanabilir Yapay Zekâ",
    author: "Kolektif (Şeref Sağıroğlu vd.)",
    category: "Uygulama",
    description: "Türk akademisyenler, XAI üzerine seri 4. cilt · Nobel Akademik Yayıncılık · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_022",
    title: "Sağlık Hizmetlerinde Yapay Zekâ",
    author: "Hüseyin Yönden",
    category: "Uygulama",
    description: "Türk yazar, sağlık sektöründe AI uygulamaları · Akademisyen Kitabevi · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_023",
    title: "Designing Machine Learning Systems",
    author: "Chip Huyen",
    category: "Uygulama",
    description: "Üretim ortamında ML sistem tasarımı, MLOps standardı · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/13314480-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_024",
    title: "Generative Deep Learning (2. baskı)",
    author: "David Foster",
    category: "Uygulama",
    description: "VAE, GAN, difüzyon ve transformer mimarileri ile üretici modeller · O'Reilly · 2023",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_025",
    title: "Generative AI Design Patterns",
    author: "Valliappa Lakshmanan & Hannes Hapke",
    category: "Uygulama",
    description: "GenAI ajanları ve uygulamaları için 32 tasarım deseni: RAG, akıl yürütme, korkuluklar · O'Reilly · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_026",
    title: "Python for Data Analysis (3. baskı)",
    author: "Wes McKinney",
    category: "Uygulama",
    description: "Pandas'ın yaratıcısından veri analizi temel referansı · O'Reilly · 2022",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_027",
    title: "Practical Statistics for Data Scientists (2. baskı)",
    author: "Peter Bruce, Andrew Bruce & Peter Gedeck",
    category: "Uygulama",
    description: "Veri bilimi için uygulamalı istatistik, Python + R örnekli · O'Reilly · 2020",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_028",
    title: "Artificial Intelligence: A Modern Approach (4. baskı)",
    author: "Stuart Russell & Peter Norvig",
    category: "Uygulama",
    description: "Dünyada en yaygın okutulan AI ders kitabı, kapsamlı akademik referans · Pearson · 2020",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_029",
    title: "Deep Learning",
    author: "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
    category: "Uygulama",
    description: "Derin öğrenmenin teorik temel referansı, akademik standart · MIT Press · 2016",
    coverImageUrl: "https://covers.openlibrary.org/b/id/8086288-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_030",
    title: "Reinforcement Learning: An Introduction (2. baskı)",
    author: "Richard S. Sutton & Andrew G. Barto",
    category: "Uygulama",
    description: "Pekiştirmeli öğrenmenin kurucu ders kitabı · MIT Press · 2018",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_031",
    title: "Fundamentals of Data Engineering",
    author: "Joe Reis & Matt Housley",
    category: "Uygulama",
    description: "Veri mühendisliği yaşam döngüsü, modern veri mimarisi referansı · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14831765-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_032",
    title: "Uygulamalı Siber Güvenlik ve Hacking",
    author: "Mustafa Altınkaynak",
    category: "Uygulama",
    description: "Türk yazar, sızma testleri ve uygulamalı güvenlik; AI sistem güvenliği için temel · Abaküs Kitap · 2021",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_033",
    title: "Üretken Yapay Zekâ ve Prompt Mühendisliği: 200+ Prompt Örneği",
    author: "Ezgi Avcı (Dr.)",
    category: "LLM & Prompt",
    description: "Türkiye'nin bu alandaki ilk özgün Türkçe kitabı · Seçkin Yayıncılık · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_034",
    title: "AI Engineering: Building Applications with Foundation Models",
    author: "Chip Huyen",
    category: "LLM & Prompt",
    description: "Production-grade LLM/agent mimarisi · O'Reilly · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_035",
    title: "Co-Intelligence: Living and Working with AI",
    author: "Ethan Mollick",
    category: "LLM & Prompt",
    description: "Wharton profesörü, Türkçesi henüz yok · Portfolio · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_036",
    title: "Hands-On Large Language Models",
    author: "Jay Alammar & Maarten Grootendorst",
    category: "LLM & Prompt",
    description: "Görsel ağırlıklı, sezgisel LLM rehberi · O'Reilly · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15155393-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_037",
    title: "Natural Language Processing with Transformers",
    author: "Lewis Tunstall, Leandro von Werra & Thomas Wolf",
    category: "LLM & Prompt",
    description: "Hugging Face ekibinden transformer tabanlı NLP uygulamaları · O'Reilly · 2022",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14559602-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_038",
    title: "Prompt Engineering for Generative AI",
    author: "James Phoenix & Mike Taylor",
    category: "LLM & Prompt",
    description: "GPT-4 ve difüzyon modelleri için güvenilir prompt teknikleri · O'Reilly · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/15103033-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_039",
    title: "LLM Engineer's Handbook",
    author: "Paul Iusztin & Maxime Labonne",
    category: "LLM & Prompt",
    description: "RAG, fine-tuning, LLMOps — üretim hattı uçtan uca; 2026 listelerinin gözdesi · Packt · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_040",
    title: "AI Agents in Action",
    author: "Micheal Lanham",
    category: "LLM & Prompt",
    description: "AI ajanları: araç kullanımı, bellek, planlama, çoklu-ajan koordinasyonu · Manning · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_041",
    title: "Building Applications with AI Agents",
    author: "Michael Albada",
    category: "LLM & Prompt",
    description: "Çoklu-ajan sistemlerin tasarımı ve üretimde uygulanması · O'Reilly · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_042",
    title: "Generative AI with LangChain (2. baskı)",
    author: "Ben Auffarth & Leonid Kuligin",
    category: "LLM & Prompt",
    description: "LangChain/LangGraph ile üretici AI ve ajan uygulamaları geliştirme · Packt · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_043",
    title: "RAG-Driven Generative AI",
    author: "Denis Rothman",
    category: "LLM & Prompt",
    description: "RAG mimarileri, vektör veritabanları, kurumsal veriyle LLM entegrasyonu · Packt · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_044",
    title: "Yapay Zekâ ve Yeni Dünya Düzeni: Çin–Silikon Vadisi",
    author: "Kai-Fu Lee",
    category: "İş & Strateji",
    description: "Eski adı AI Superpowers · Optimist Yayın Grubu · 2018",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_045",
    title: "Geleceğin Endüstrileri",
    author: "Alec Ross",
    category: "İş & Strateji",
    description: "Teknoloji trendleri · Orion Kitabevi · 2017",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_046",
    title: "Sıfırdan Bire",
    author: "Peter Thiel & Blake Masters",
    category: "İş & Strateji",
    description: "İnovasyon, girişimcilik klasik · Pegasus Yayınları · 2016",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_047",
    title: "Yalın Startup",
    author: "Eric Ries",
    category: "İş & Strateji",
    description: "MVP, pivot, deneysel girişimcilik · Maltepe Üniversitesi Kitapları · 2019",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12215222-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_048",
    title: "Kancaya Takılınca",
    author: "Nir Eyal & Ryan Hoover",
    category: "İş & Strateji",
    description: "Ürün, pazarlama, davranış tasarımı · Nova Yayınevi · 2022",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_049",
    title: "Sprint: 5 Günde Büyük Sorunları Çözün",
    author: "Jake Knapp, Zeratsky, Kowitz",
    category: "İş & Strateji",
    description: "Google Ventures tasarım sprint · Buzdağı Yayınevi · 2017",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_050",
    title: "Yapay Zekâ Devrimi",
    author: "Bernard Marr",
    category: "İş & Strateji",
    description: "AI'nın iş dünyasına etkisi, sektör örnekleri · Kronik Kitap · 2023",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_051",
    title: "Pazarlama ve Ürün İnovasyonunda Yapay Zeka",
    author: "A. K. Pradeep",
    category: "İş & Strateji",
    description: "Büyük veri + AI + pazarlama · Optimist Kitap · 2020",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_052",
    title: "Yapay Zeka ve Dijital Pazarlama Aşkı",
    author: "Yasin Kaplan",
    category: "İş & Strateji",
    description: "Türk yazar, dijital reklamda AI uygulamaları · Dijital Pazarlama Okulu · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_053",
    title: "Yapay Zekâ Çağında Modern Pazarlama Stratejileri",
    author: "Nurettin Alabay (Dr.)",
    category: "İş & Strateji",
    description: "Türk yazar, AI + pazarlama stratejisi · Akademisyen Yayınları · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_054",
    title: "Tahmin Eden Makineler: Yapay Zekanın Basit Ekonomisi",
    author: "Ajay Agrawal, Joshua Gans & Avi Goldfarb",
    category: "İş & Strateji",
    description: "AI ekonomisi, ChatGPT öncesi klasik analiz · Buzdağı Yayınevi · 2019",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_055",
    title: "Supremacy: AI, ChatGPT, and the Race That Will Change the World",
    author: "Parmy Olson",
    category: "İş & Strateji",
    description: "FT Yılın İş Kitabı 2024; OpenAI–DeepMind rekabetinin perde arkası · St. Martin's Press · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_056",
    title: "The AI-Savvy Leader",
    author: "David De Cremer",
    category: "İş & Strateji",
    description: "Yöneticiler için AI dönüşümünü yönetme rehberi · HBR Press · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_057",
    title: "Süper Zekâ",
    author: "Nick Bostrom",
    category: "Etik & Toplum",
    description: "AI riskleri klasik · Koç Üniversitesi Yayınları · 2014",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12116498-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_058",
    title: "Robotların Yükselişi",
    author: "Martin Ford",
    category: "Etik & Toplum",
    description: "Otomasyon ve istihdam · Kronik Kitap · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12303850-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_059",
    title: "Yaklaşan Dalga",
    author: "Mustafa Suleyman & Michael Bhaskar",
    category: "Etik & Toplum",
    description: "DeepMind/Microsoft AI kurucusu, GenAI çağı · Doğan Kitap · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_060",
    title: "Gözetim Kapitalizmi Çağı",
    author: "Shoshana Zuboff",
    category: "Etik & Toplum",
    description: "Veri kapitalizmi, hukuk/İK için kritik · Pegasus Yayınları · 2021",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_061",
    title: "Merhaba Dünya: Makine Çağında İnsan Olmak",
    author: "Hannah Fry",
    category: "Etik & Toplum",
    description: "Algoritmaların adalet/sağlık/suç alanındaki etkisi · HEP Kitap · 2020",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_062",
    title: "Yeni Dünya, Yeni Ağ",
    author: "Cem Say",
    category: "Etik & Toplum",
    description: "Türk yazar, internet ve toplum · Bilim ve Gelecek Kitaplığı · 2020",
    coverImageUrl: "https://covers.openlibrary.org/b/id/12121736-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_063",
    title: "Yapay Zeka ve Hukuk",
    author: "Kolektif (Editör: Mustafa Erdem Can)",
    category: "Etik & Toplum",
    description: "Türk hukukçular, AI hukuki boyutu, KVKK · Seçkin Yayıncılık · 2023",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_064",
    title: "Yapay Zekâ Çağında İnsan Kaynakları",
    author: "Kolektif",
    category: "Etik & Toplum",
    description: "İK profesyonelleri için AI'nın etkileri · Akademisyen Yayınevi · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_065",
    title: "Empire of AI: Dreams and Nightmares in Sam Altman's OpenAI",
    author: "Karen Hao",
    category: "Etik & Toplum",
    description: "OpenAI üzerine araştırmacı gazetecilik; NYT çok satanı, ödül finalisti · Penguin Press · 2025",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_066",
    title: "Homo Deus: Yarının Kısa Bir Tarihi",
    author: "Yuval Noah Harari",
    category: "İlham",
    description: "Gelecek, insanlık, AI · Kolektif Kitap · 2016",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_067",
    title: "21. Yüzyıl İçin 21 Ders",
    author: "Yuval Noah Harari",
    category: "İlham",
    description: "Dijital çağ · Kolektif Kitap · 2018",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_068",
    title: "İnsanlık 2.0: Tekilliğe Doğru",
    author: "Ray Kurzweil",
    category: "İlham",
    description: "Tekillik klasiği · NTV Yayınları · 2009",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_069",
    title: "En Hakiki Mürşit",
    author: "Cem Say",
    category: "İlham",
    description: "Türk yazar, bilim felsefesi · Bilim ve Gelecek Kitaplığı · 2018",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_070",
    title: "Nexus: Bilgi Ağlarının Kısa Tarihi",
    author: "Yuval Noah Harari",
    category: "İlham",
    description: "Harari'nin en yeni kitabı, AI'nın bilgi ağlarına etkisi · Kolektif Kitap · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_071",
    title: "Architects of Intelligence",
    author: "Martin Ford",
    category: "İlham",
    description: "AI öncüleriyle 23 derinlemesine röportaj · Packt Publishing · 2018",
    coverImageUrl: "https://covers.openlibrary.org/b/id/9351056-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_072",
    title: "Kuantum Üstünlüğü",
    author: "Michio Kaku",
    category: "İlham",
    description: "Kuantum bilgisayar devrimi ve AI'ya etkisi; güncel teknoloji vizyonu · ODTÜ Yayıncılık · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_073",
    title: "The Singularity Is Nearer",
    author: "Ray Kurzweil",
    category: "İlham",
    description: "Kurzweil'in 2024'te güncellediği tekillik ve AGI öngörüleri · Viking · 2024",
    coverImageUrl: "https://covers.openlibrary.org/b/id/14861631-L.jpg",
    totalCopies: 2,
  },
  {
    id: "book_xl_074",
    title: "Genesis: Artificial Intelligence, Hope, and the Human Spirit",
    author: "Henry Kissinger, Eric Schmidt & Craig Mundie",
    category: "İlham",
    description: "AI çağında insanlık, güç ve gelecek üzerine stratejik bakış · Little, Brown · 2024",
    coverImageUrl: null,
    totalCopies: 2,
  },
  {
    id: "book_xl_075",
    title: "The Worlds I See",
    author: "Fei-Fei Li",
    category: "İlham",
    description: "ImageNet'in yaratıcısından AI tarihine tanıklık eden anı kitabı · Flatiron Books · 2023",
    coverImageUrl: null,
    totalCopies: 2,
  },
];
