/**
 * Merkezi error code katalogu.
 *
 * Güvenlik:
 * - app_security.md §8: Kullanıcıya generic mesaj, kod ile machine-readable.
 * - Frontend bu kodlara göre i18n + retry stratejisi belirler.
 * - Kodların değeri DEĞİŞMEZ (frontend regression'a sebep olur).
 */

export const ErrorCodes = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FAILED: 'AUTH_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
  REFRESH_INVALID: 'REFRESH_INVALID',
  REFRESH_REUSE: 'REFRESH_REUSE',

  // MFA
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  MFA_NOT_ENABLED: 'MFA_NOT_ENABLED',

  // CSRF
  CSRF_INVALID: 'CSRF_INVALID',
  CSRF_MISSING: 'CSRF_MISSING',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  INVALID_ID: 'INVALID_ID',

  // Booking
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_NOT_AVAILABLE: 'ROOM_NOT_AVAILABLE',
  ROOM_CONFLICT: 'ROOM_CONFLICT',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_NOT_EDITABLE: 'BOOKING_NOT_EDITABLE',
  BOOKING_NOT_WITHDRAWABLE: 'BOOKING_NOT_WITHDRAWABLE',
  INVALID_START_DATE: 'INVALID_START_DATE',

  // Waitlist
  WAITLIST_ALREADY_JOINED: 'WAITLIST_ALREADY_JOINED',
  WAITLIST_ENTRY_NOT_FOUND: 'WAITLIST_ENTRY_NOT_FOUND',
  WAITLIST_ROOM_AVAILABLE: 'WAITLIST_ROOM_AVAILABLE',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_DELETED: 'ALREADY_DELETED',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  RATE_LIMIT: 'RATE_LIMIT',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
